# Generated by Django 5.0.6 on 2024-06-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScrapingJob",
            fields=[
                ("job_id", models.UUIDField(primary_key=True, serialize=False)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("result", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
